[package]
name = "v2r"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
ratatui = "0.28"
crossterm = "0.28"
